[cmake] new option for XDG autostart support

diff --git a/rootfs/usr/bin/bianbu-ai-autotools b/rootfs/usr/bin/bianbu-ai-autotools
--- a/rootfs/usr/bin/bianbu-ai-autotools
+++ b/rootfs/usr/bin/bianbu-ai-autotools
@@ -87,4 +87,7 @@ function auto_config_desktop() {
 
 if [[ $cmd == "desktop" ]]; then
   auto_config_desktop $@
+else
+  echo "[ERROR] Unknown command: ${cmd}"
+  exit 1
 fi
